# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # Run tests
  desc "Run tests"
  lane :tests do
    scan(
      scheme: "LetSki",
      clean: true,
      skip_package_dependencies: true,  # Prevent resolving package dependencies
      device: "iPhone 15 Pro",  # Adjust the simulator device if needed
      result_bundle: true        # Generate result bundle for easier debugging
    )
  end

  # Build the app
  desc "Build the app"
  lane :build do
    gym(
      scheme: "LetSki",               # The name of your scheme
      clean: true,                    # Clean the build before running
      output_directory: "./build",    # Output directory for the built IPA
      output_name: "LetSki.ipa",      # Name of the generated IPA file
      configuration: "Release",       # Build configuration (could be 'Release' or 'Debug')
      export_method: "development",   # Export method (can also be 'app-store', 'ad-hoc', etc.)
      silent: false                   # Show full output for debugging
    )
  end
end
