# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    scan(
      scheme: "LetSki",
      clean: true
    )
  end
end

default_platform(:ios)

lane :build do
  gym(
    scheme: "LetSki",              
    clean: true,                     
    output_directory: "./build",     
    output_name: "LetSki.ipa",      
    configuration: "Release",        
    export_method: "development",     
    silent: false                     
  )
end
