name: iOS CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

#      - name: Install dependencies
#        run: bundle install --path vendor/bundle
#
#      - name: Clean Build Folder
#        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*
#
#      - name: List available Xcode versions (Debugging)
#        run: ls /Applications | grep Xcode

      - name: Run tests
        run: bundle exec fastlane tests
