name: iOS CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Debug - Check Xcode Version
        run: xcodebuild -version

      - name: Install Needle
        run: brew install needle

      - name: Clean Build Folder
        run: |
          xcodebuild -skipMacroValidation clean -scheme LetSki
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Resolve Swift Packages
        run: xcodebuild -skipMacroValidation -resolvePackageDependencies -scheme LetSki

      - name: Generate Needle Dependencies
        run: needle generate "$GITHUB_WORKSPACE/NeedleGenerated.swift" "$GITHUB_WORKSPACE"

      - name: Verify NeedleGenerated.swift exists
        run: ls -l "$GITHUB_WORKSPACE"

      - name: Build the project
        run: |
          xcodebuild -skipMacroValidation build \
            -project LetSki.xcodeproj \
            -scheme LetSki \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run unit tests only (skip UI tests)
        run: |
          xcodebuild -skipMacroValidation test \
            -project LetSki.xcodeproj \
            -scheme LetSki \
            -only-testing:LetSkiTests \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            | xcpretty && exit ${PIPESTATUS[0]}
