name: iOS CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Debug - Check Xcode Version
        run: xcodebuild -version

      - name: Clean Build Folder
        run: |
          xcodebuild -skipMacroValidation clean -scheme LetSki
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # - name: Force Swift 5.9 (Prevent Swift 6 Issues)
      #   run: echo "swift-tools-version:5.9" > .swift-version

      - name: Resolve Swift Packages
        run: xcodebuild -skipMacroValidation -resolvePackageDependencies -scheme LetSki

      # - name: Build Swift Macros
      #   run: |
      #     xcodebuild -skipMacroValidation build \
      #       -scheme LetSki \
      #       -target ComposableArchitectureMacros \
      #       -destination 'platform=macOS'

      #     xcodebuild -skipMacroValidation build \
      #       -scheme LetSki \
      #       -target CasePathsMacros \
      #       -destination 'platform=macOS'

      #     xcodebuild -skipMacroValidation build \
      #       -scheme LetSki \
      #       -target DependenciesMacrosPlugin \
      #       -destination 'platform=macOS'

      #     xcodebuild -skipMacroValidation build \
      #       -scheme LetSki \
      #       -target PerceptionMacros \
      #       -destination 'platform=macOS'

      - name: Build the project
        run: |
          xcodebuild -skipMacroValidation build \
            -project LetSki.xcodeproj \
            -scheme LetSki \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run unit tests only (skip UI tests)
        run: |
          xcodebuild -skipMacroValidation test \
            -project LetSki.xcodeproj \
            -scheme LetSki \
            -only-testing:LetSkiTests \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            | xcpretty && exit ${PIPESTATUS[0]}
