name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec fastlane scan

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app  # Adjust version
      - name: Install Dependencies
        run: bundle install
      - name: Build App
        run: bundle exec fastlane build
