name: iOS CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Debug - Check Xcode Version
        run: xcodebuild -version

      - name: Clean Build Folder
        run: |
          xcodebuild clean -scheme LetSki
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Force Swift 5.9 (Prevent Swift 6 Issues)
        run: echo "swift-tools-version:5.9" > .swift-version

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies -scheme LetSki

      - name: Build Swift Macros
        run: |
          SKIP_MACRO_VALIDATION=YES xcodebuild build \
            -scheme LetSki \
            -target ComposableArchitectureMacros \
            -destination 'platform=macOS'

          SKIP_MACRO_VALIDATION=YES xcodebuild build \
            -scheme LetSki \
            -target CasePathsMacros \
            -destination 'platform=macOS'

          SKIP_MACRO_VALIDATION=YES xcodebuild build \
            -scheme LetSki \
            -target DependenciesMacrosPlugin \
            -destination 'platform=macOS'

          SKIP_MACRO_VALIDATION=YES xcodebuild build \
            -scheme LetSki \
            -target PerceptionMacros \
            -destination 'platform=macOS'

      - name: Build the project
        run: |
          SKIP_MACRO_VALIDATION=YES xcodebuild build \
            -project LetSki.xcodeproj \
            -scheme LetSki \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run tests
        run: |
          SKIP_MACRO_VALIDATION=YES xcodebuild test \
            -project LetSki.xcodeproj \
            -scheme LetSki \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            | xcpretty && exit ${PIPESTATUS[0]}
